import { ArrestRecord } from "./types";

/**
 * Clearly-marked SAMPLE data used only when Supabase is not configured,
 * so the site can be previewed locally. Every person below is fictional
 * and every arrest number is prefixed with "SAMPLE-".
 */

function rec(partial: Partial<ArrestRecord> & { id: string }): ArrestRecord {
  return {
    source: "sample",
    county: "Broward",
    arrest_number: "SAMPLE-0000",
    first_name: null,
    middle_name: null,
    last_name: null,
    full_name: "Sample Person",
    sex: null,
    age: null,
    booking_date: null,
    arrest_date: null,
    release_date: null,
    location: null,
    charges_json: null,
    bond_json: null,
    charges_text: null,
    mugshot_url: null,
    official_detail_url: "https://bookingblotter.sheriff.org/app/",
    status: "published",
    is_hidden: false,
    hidden_reason: null,
    mugshot_hidden: false,
    removal_requested: false,
    removal_requested_at: null,
    removed_at: null,
    created_at: "2026-07-01T09:00:00Z",
    updated_at: "2026-07-01T09:00:00Z",
    ...partial,
  };
}

export const SAMPLE_ARRESTS: ArrestRecord[] = [
  rec({
    id: "sample-1",
    arrest_number: "SAMPLE-2026-0001",
    first_name: "Jordan",
    last_name: "Exampleton",
    full_name: "Jordan Exampleton",
    sex: "M",
    age: 34,
    booking_date: "2026-07-05",
    arrest_date: "2026-07-05",
    location: "Fort Lauderdale, FL",
    charges_json: [
      { description: "Driving under the influence", statute: "316.193", bond_amount: "$1,000" },
    ],
    charges_text: "Driving under the influence 316.193",
    bond_json: { total_bond: "$1,000", bond_type: "Surety" },
  }),
  rec({
    id: "sample-2",
    arrest_number: "SAMPLE-2026-0002",
    first_name: "Casey",
    middle_name: "R",
    last_name: "Demoson",
    full_name: "Casey R Demoson",
    sex: "F",
    age: 27,
    booking_date: "2026-07-05",
    arrest_date: "2026-07-04",
    location: "Pompano Beach, FL",
    charges_json: [
      { description: "Battery (touch or strike)", statute: "784.03", bond_amount: "$2,500" },
    ],
    charges_text: "Battery (touch or strike) 784.03",
    bond_json: { total_bond: "$2,500", bond_type: "Surety" },
  }),
  rec({
    id: "sample-3",
    arrest_number: "SAMPLE-2026-0003",
    first_name: "Morgan",
    last_name: "Placeholder",
    full_name: "Morgan Placeholder",
    sex: "M",
    age: 41,
    booking_date: "2026-07-04",
    arrest_date: "2026-07-04",
    location: "Hollywood, FL",
    charges_json: [
      { description: "Possession of a controlled substance", statute: "893.13", bond_amount: "$3,500" },
      { description: "Possession of drug paraphernalia", statute: "893.147", bond_amount: "$500" },
    ],
    charges_text:
      "Possession of a controlled substance 893.13; Possession of drug paraphernalia 893.147",
    bond_json: { total_bond: "$4,000", bond_type: "Surety" },
  }),
  rec({
    id: "sample-4",
    arrest_number: "SAMPLE-2026-0004",
    first_name: "Riley",
    last_name: "Testcase",
    full_name: "Riley Testcase",
    sex: "F",
    age: 30,
    booking_date: "2026-07-04",
    location: "Deerfield Beach, FL",
    charges_json: [
      { description: "Petit theft (second offense)", statute: "812.014", bond_amount: "$1,000" },
    ],
    charges_text: "Petit theft (second offense) 812.014",
  }),
  rec({
    id: "sample-5",
    arrest_number: "SAMPLE-2026-0005",
    first_name: "Avery",
    last_name: "Mockman",
    full_name: "Avery Mockman",
    sex: "M",
    age: 52,
    booking_date: "2026-07-03",
    location: "Coral Springs, FL",
    charges_json: [
      { description: "Domestic violence battery", statute: "741.28", bond_amount: "No bond" },
    ],
    charges_text: "Domestic violence battery 741.28",
    bond_json: { total_bond: "No bond", bond_type: "Hold" },
  }),
  rec({
    id: "sample-6",
    arrest_number: "SAMPLE-2026-0006",
    first_name: "Quinn",
    last_name: "Fakerly",
    full_name: "Quinn Fakerly",
    sex: "F",
    age: 23,
    booking_date: "2026-07-03",
    location: "Lauderhill, FL",
    charges_json: [
      { description: "Driving while license suspended", statute: "322.34", bond_amount: "$250" },
      { description: "Reckless driving", statute: "316.192", bond_amount: "$500" },
    ],
    charges_text: "Driving while license suspended 322.34; Reckless driving 316.192",
  }),
  rec({
    id: "sample-7",
    arrest_number: "SAMPLE-2026-0007",
    first_name: "Drew",
    last_name: "Specimen",
    full_name: "Drew Specimen",
    sex: "M",
    age: 38,
    booking_date: "2026-07-02",
    location: "Plantation, FL",
    charges_json: [
      { description: "Violation of probation (felony)", statute: "948.06", bond_amount: "No bond" },
    ],
    charges_text: "Violation of probation (felony) 948.06",
  }),
  rec({
    id: "sample-8",
    arrest_number: "SAMPLE-2026-0008",
    first_name: "Skyler",
    last_name: "Dataset",
    full_name: "Skyler Dataset",
    sex: "F",
    age: 45,
    booking_date: "2026-07-02",
    location: "Sunrise, FL",
    charges_json: [
      { description: "Grand theft (third degree)", statute: "812.014(2)(c)", bond_amount: "$5,000" },
      { description: "Fraudulent use of a credit card", statute: "817.61", bond_amount: "$2,500" },
    ],
    charges_text:
      "Grand theft (third degree) 812.014(2)(c); Fraudulent use of a credit card 817.61",
  }),
  rec({
    id: "sample-9",
    arrest_number: "SAMPLE-2026-0009",
    first_name: "Reese",
    last_name: "Exemplar",
    full_name: "Reese Exemplar",
    sex: "M",
    age: 29,
    booking_date: "2026-07-01",
    location: "Tamarac, FL",
    charges_json: [
      {
        description: "Carrying a concealed firearm without a license",
        statute: "790.01",
        bond_amount: "$7,500",
      },
    ],
    charges_text: "Carrying a concealed firearm without a license 790.01",
  }),
  rec({
    id: "sample-10",
    arrest_number: "SAMPLE-2026-0010",
    first_name: "Peyton",
    last_name: "Standin",
    full_name: "Peyton Standin",
    sex: "F",
    age: 33,
    booking_date: "2026-07-01",
    location: "Miramar, FL",
    charges_json: [
      { description: "Burglary of an unoccupied dwelling", statute: "810.02", bond_amount: "$10,000" },
    ],
    charges_text: "Burglary of an unoccupied dwelling 810.02",
  }),
  rec({
    id: "sample-11",
    arrest_number: "SAMPLE-2026-0011",
    first_name: "Emerson",
    last_name: "Nulldata",
    full_name: "Emerson Nulldata",
    sex: "M",
    age: 60,
    booking_date: "2026-06-30",
    release_date: "2026-07-01",
    location: "Pembroke Pines, FL",
    charges_json: [
      { description: "Trespass on property", statute: "810.09", bond_amount: "$100" },
    ],
    charges_text: "Trespass on property 810.09",
  }),
  rec({
    id: "sample-12",
    arrest_number: "SAMPLE-2026-0012",
    first_name: "Harper",
    last_name: "Blankfield",
    full_name: "Harper Blankfield",
    sex: "F",
    age: 26,
    booking_date: "2026-06-30",
    location: "Davie, FL",
    charges_json: [
      { description: "Possession of cannabis over 20 grams", statute: "893.13", bond_amount: "$1,500" },
    ],
    charges_text: "Possession of cannabis over 20 grams 893.13",
  }),
];
